spring:
  application:
    name: warehouse_inventory_management
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false # Запуск через докер, в котором отдельный контейнер для LB