spring:
  application:
    name: warehouse_inventory_management
  datasource:
    url: "jdbc:postgresql://localhost:5430/pg_db"
    username: user
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create-drop