-- liquibase formatted sql

-- changeset Petra:1787037025929-1
CREATE SEQUENCE IF NOT EXISTS item_id_seq START WITH 1 INCREMENT BY 1;

-- changeset Petra:1787037025929-2
CREATE SEQUENCE IF NOT EXISTS operation_id_seq START WITH 1 INCREMENT BY 1;

-- changeset Petra:1787037025929-3
CREATE SEQUENCE IF NOT EXISTS storage_id_seq START WITH 1 INCREMENT BY 1;

-- changeset Petra:1787037025929-4
CREATE TABLE item
(
    count      INTEGER,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storage_id BIGINT,
    item       VARCHAR(255),
    status     VARCHAR(255),
    CONSTRAINT item_pkey PRIMARY KEY (id)
);

-- changeset Petra:1787037025929-5
CREATE TABLE operation
(
    amount              INTEGER,
    id                  BIGINT NOT NULL,
    operation_date_time TIMESTAMP WITHOUT TIME ZONE,
    operation_type      VARCHAR(255),
    product_name        VARCHAR(255),
    storage_name        VARCHAR(255),
    comment             VARCHAR(255),
    CONSTRAINT operation_pkey PRIMARY KEY (id)
);

-- changeset Petra:1787037025929-6
CREATE TABLE storage
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT storage_pkey PRIMARY KEY (id)
);

